# Generated by Django 5.0.2 on 2024-03-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylink',
            old_name='tittle',
            new_name='title',
        ),
    ]
